version: '3.8'

services:
  database:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/script/db_springboot_api.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monrezo

  api:
    image: bazurogg/apispringboot2025:latest
    container_name: api-container
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/springboot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: groot
    ports:
      - "9000:9000"
    networks:
      - monrezo

  webapp:
    image: bazurogg/webspringboot2025:latest
    container_name: webapp-container
    restart: always
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:9000
    ports:
      - "9090:9090"
    networks:
      - monrezo

volumes:
  mysql_data:

networks:
  monrezo:
    driver: bridge
